export const LOGIN_IN  =  'LOGIN_IN';
export const LOGIN_FAILED  =  'LOGIN_FAILED';
export const REGISTER  =  'REGISTER';
export const LOGOUT  =  'LOGOUT';
export const REGISTER_FAILED  =  'REGISTER_FAILED';
export const REGISTER_FINISHED  =  'REGISTER_FINISHED';
export const REGISTER_FINISHED_FAILED  =  'REGISTER_FINISHED_FAILED';
export const LOGIN_IF_IN_SYSTEM  =  'LOGIN_IF_IN_SYSTEM';
